# Use a minimal base image
FROM alpine:latest

# Set the working directory
WORKDIR /app

# Copy the cleanup script into the container
COPY ./cleanup_download_files.sh /app/cleanup_download_files.sh

# Make the script executable
RUN chmod +x /app/cleanup_download_files.sh

# Run the cleanup script every 5 minutes
CMD ["sh", "-c", "while true; do /app/cleanup_download_files.sh; sleep 600; done"]